### ISSUE TITLE
Generated clang compilation database contains invalid trailing comma after last compile command

### ISSUE THREAD

**Issue by dakotahawkins** [CoatiSoftware/vs-sourcetrail#10]
This is [not allowed in JSON](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#Trailing_commas_in_JSON), and clang tools don't seem to like it.

I hope to have a PR up shortly.

**Comment by mlangkabel** [comment]
Hi @dakotahawkins, thanks for bringing this up. I'll look at your pull request right away.

**Comment by mlangkabel** [comment]
Fixed by merging pull request #11. New release is available on Github as well as on the Visual Studio Marketplace.
