### ISSUE TITLE
Incomplete project properties

### ISSUE THREAD

**Issue by dakotahawkins** [CoatiSoftware/vs-sourcetrail#12]
I found that in a certain case, I wasn't getting all of the preprocessor definitions that were present:

In a property sheet:

```xml
<ItemDefinitionGroup>
  <ClCompile>
     <PreprocessorDefinitions>NOMINMAX;%(PreprocessorDefinitions)</PreprocessorDefinitions>
  </ClCompile>
<ItemDefinitionGroup>
<ItemDefinitionGroup Condition="'$(Configuration)'=='Debug'">
  <ClCompile>
    <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
  </ClCompile>
</ItemDefinitionGroup>
```

In a project including the property sheet:

```xml
<ItemDefinitionGroup Condition="'$(Configuration)'=='Debug'">
  <ClCompile>
    <PreprocessorDefinitions>%(PreprocessorDefinitions)</PreprocessorDefinitions>
  </ClCompile>
</ItemDefinitionGroup>
```

In this case, I was missing `NOMINMAX`. I'm not sure why, but the functionality that was being used to get these values just left it out.

The tool wrappers can each cast their wrapped objects to an IVCRulePropertyStorage, which does return the correct information. It also handles property sheets and everything else, so it should simplify the code a lot.

I'll have a PR up shortly.

**Comment by mlangkabel** [comment]
Property sheets are a little bit tricky to handle. Especially in cases where the project defines not to use the property sheets (we have tests for that, but I noticed that you changed these tests on your fork (a1fe9d91931346942eb5656691c409f70ea5f609) so they may not be working correctly anymore).

We really appreciate your work on this project! To make things a little bit easier for us I wanted to ask you to keep pull requests as small as possible, so that we don't have to consider too many changes in the reviews. Better issue many small pull requests than one big one. That would let us pull smaller changes more quickly.

For example I'd really like to pull those first three commits on your branch right now ;)

**Comment by dakotahawkins** [comment]
If you look at the diff, I think the changes were all because of the relative path thing. The behavior is the same.

The change in https://github.com/CoatiSoftware/vs-sourcetrail/pull/13/commits/b15a7c7eb8f4133144a6b60b6ba09a0b96a7fb53 to the way those properties are retrieved handles property sheets beautifully. Visual Studio knows what the fully evaluated (including property sheets if necessary) properties are, and this is one of the (many) ways to ask for that.

The "problem" this caused that got me started trying to use project-relative paths is that now those properties are returned from the start as full paths with their macros fully evaluated. That's great for real-world use, since it's what you want, **but** that's bad for the unit tests. Without the macros in the property strings, the current method of faking property evaluation doesn't apply so the test output contains machine-specific full paths were before it didn't.

**Comment by dakotahawkins** [comment]
The fix in https://github.com/dakotahawkins/vs-sourcetrail/commit/857429fe994f5a0875bcf6d5aa48118027720b43 is pretty much the same as before. It's by itself (though on top of the commits in #15, so I'm waiting for that to get resolved). The tests all pass with a small modification to [`TestPathResolver.GetAsAbsoluteCanonicalPath()`](https://github.com/dakotahawkins/vs-sourcetrail/commit/857429fe994f5a0875bcf6d5aa48118027720b43#diff-5cb6d073f85cff047f04a900ac0d89f9) that re-inserts the `$(ProjectDir)` macro in resolved paths.

**Comment by dakotahawkins** [comment]
Actually, I can make my other branches independant of #15 (I just need #15 to run tests), so I'll go ahead and submit PRs.
