### ISSUE TITLE
Compile commands should use paths relative to project directory

### ISSUE THREAD

**Issue by dakotahawkins** [CoatiSoftware/vs-sourcetrail#14]
Instead of using paths relative to the compilation database, project-relative paths should be a little closer to visual studio's behavior and avoid making exact duplicates in the case two projects reference the same file.

This will also avoid more dummy macro-evaluations in the unit tests.

**Comment by dakotahawkins** [comment]
Based on failures with my real-world solution, this might not be workable :(

Feel free to close this if you think that's the case.

**Comment by mlangkabel** [comment]
We testes this, too and it isn't working for us either.

Relative paths would provide the benefit that if you put his compilation database inside the version control next to the project's source files you could the move the project's root folder everywhere you wanted. But on the other hand side, the compilation database is a generated file that shouldn't be part of the version control anyway. And moving the compilation database file would break all those relative paths. 

So I think we'll just stick to absolute paths for now.
