### ISSUE TITLE
Missing implied preprocessor definitions cause clang errors

### ISSUE THREAD

**Issue by dakotahawkins** [CoatiSoftware/vs-sourcetrail#18]
If `_AFXDLL` is in your preprocessor definitions, you will get the following clang diagnostic error from some windows header(s):

"error: Please use the /MD switch for _AFXDLL builds"

Setting "Use of MFC in a Shared DLL" will get you `_AFXDLL` automatically, but the code that emits this error is looking for `_DLL`. That doesn't normally come from preprocessor definitions explicitly, it's controlled by the project's runtime library setting.

We should check the runtime library setting and add the appropriate implied defines to the preprocessor definitions. There are probably a lot more of these that might turn out to be necessary, but this is the only diagnostic error I've encountered so far. See [here](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros) for a list of candidates.

~~I will probably have to tack my fix on to #16, because it will modify the same code.~~

There is a merge conflict in one of the test json files, it would go in cleanly after the others, so I'll wait on that. In the meantime, you can see the proposed fix [in this commit on my fork.](https://github.com/dakotahawkins/vs-sourcetrail/commit/a6c052aefc00be74328cb747544169d6a7f1ec56#diff-7a8b5a44c49dc7cce2b81f53ff72fe05)

**Comment by mlangkabel** [comment]
I looked at the linked commit. Those changes are looking good.

**Comment by dakotahawkins** [comment]
I was thinking all around these things might go away if we could steal the whole cl.exe command line and use `--driver-mode=cl`. Only problem is there's not an API to get the whole command line (even though you can view it in the UI). I think maybe adding a fake cl.exe that captures and prints its arguments might work if you put it's path first in the `$(ExecutablePath)` and then tell the file to build.

If that did work it should take out 100% of this guess work and let clang do the lifting.
