### ISSUE TITLE
Investigate clang's cl driver to see if it will work in the compilation command database

### ISSUE THREAD

**Issue by dakotahawkins** [CoatiSoftware/vs-sourcetrail#20]
Passing `--driver-mode=cl` to clang should (maybe) let it handle the native MSVC compilation arguments as originally noted [here](https://github.com/CoatiSoftware/vs-sourcetrail/issues/18#issuecomment-334158547).

Capturing the arguments might be pretty difficult, but a manual test would indicate whether it will work in the first place.

References:

- http://releases.llvm.org/5.0.0/tools/clang/docs/MSVCCompatibility.html
- http://releases.llvm.org/5.0.0/tools/clang/docs/UsersManual.html#clang-cl
- https://llvm.org/devmtg/2014-04/PDFs/Talks/clang-cl.pdf

**Comment by dakotahawkins** [comment]
I found that it does work (pretty much as-is, which is neat, but it doesn't allow most of the clang-tidy checks to work, so this is probably a no-go.

**Comment by mlangkabel** [comment]
Even though this doesn't seem to be a feasible approach, thanks for giving it a try!
