### ISSUE TITLE
Support Visual Studio 2010

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/vs-sourcetrail#26]

**Comment by dakotahawkins** [comment]
That should be technically possible, but for what it's worth the reason it's not common is that it would require two extensions... 2010-2015 could use the same one, or 2012-2017 could use the same one, but 2010-2017 would require two.

As a workaround, could you use a newer IDE with 2010 projects? You should be able to throw a [<VCProjectUpgraderObjectName>NoUpgrade</VCProjectUpgraderObjectName>](http://connect.microsoft.com/VisualStudio/feedbackdetail/view/871523/vs-2013-keeps-upgrade-information-in-the-solution-user-options-v12-suo-file) in your project files or in a property sheet to keep the new IDE from trying to upgrade your projects.

Then I think you can just use a new IDE and keep compiling with 2010 (as long as 2010 is still installed). We do this where I work, I use 2017 as my IDE but everything builds with 2013.

**Comment by mlangkabel** [comment]
Thanks for sharing your thoughts on this issue. We decided against maintaining two different versions of the plugin. So I'll close this now.
