### ISSUE TITLE
Update Readme to mention that Intellisense/Browse Database must be enabled

### ISSUE THREAD

**Issue by Genocidicbunny** [CoatiSoftware/vs-sourcetrail#27]
I normally run VS2015 with Intellisense disabled. When trying to use the extension, the 'Create Compilation Database' option was greyed out, and the extension was logging an exception for every project in the solution:

> Error: Exception: The solution's source code database may not have been opened.  Please make sure the solution is not open in another copy of Visual Studio, and that its database file is not read only.

This caused the extension to not find any C/C++ projects in my solution despite there only being C/C++ projects in the solution.
I eventually figured out that enabling Intellisense and the Browse Database re-enables the 'Create Compilation Database' menu option.

It would be good if this was mentioned in the readme.

**Comment by mlangkabel** [comment]
Thanks @Genocidicbunny for reporting this one. We never thought of using Visual Studio with Intellisense disabled so we wouldn't have found this one by ourselves! Documenting this in the readme is a good idea.
