### ISSUE TITLE
Exporting a Compilation Database for Notepad3 has issues

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/vs-sourcetrail#3]
repo: [Notepad3](https://github.com/rizonesoft/Notepad3)

* C files have C++ standard flag
* UNICODE define missing in some cases

**Comment by mlangkabel** [comment]
For the first issue you mentioned it looks like the Sourcetrail extension does not implement the correct fallback behavior in case the `language` setting of the compiled source file is set to `default`

**Comment by mlangkabel** [comment]
I have opened two new issues so that we can keep track of each of the problems mentioned here separately.

* issue #4: C files have C++ standard flag
* issue #5: UNICODE define missing in some cases
