### ISSUE TITLE
c++14 support needed

### ISSUE THREAD

**Issue by yantaozhao** [CoatiSoftware/vs-sourcetrail#40]
`C++14` is intended to be a small extension over C++11, featuring mainly bug fixes and small improvements.
And in both visual studio 2015 and gcc/g++6, std=c++14 is specified by default.
So please support c++14 besides c++11. Thanks.
see: 
https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version
https://gcc.gnu.org/gcc-6/changes.html

**Comment by mlangkabel** [comment]
Hi @yantaozhao,  thaks for reaching out to us. What do you mean by "support"? So what is happening for you and what would be the thing you expect/want to happen?

**Comment by yantaozhao** [comment]
Currently, when using the plugin to "Create Compilation Database" in visual studio, the upmost option is `c11`. And the plugin emits some errors on the codes which was built sucessfully with VS2015.3.
I don't know whether the plugin meets my codes which use some `c++14` new feature. That's my concern.
Brs.

**Comment by mlangkabel** [comment]
The C language standard you select in the Visual Studio extention is applied only for the C files in your Visual Studio solution. Visual Studio 2015 supports C++14 and this is the C++ standard that is automatically written to the compilation database for all C++ files in your solution. So everything should be fine for you.

What errors does the plugin emit?

**Comment by yantaozhao** [comment]
Sound good. thx.
