### ISSUE TITLE
The extension is not compatible with the new Visual Studio 2019 Preview

### ISSUE THREAD

**Issue by cata0309** [CoatiSoftware/vs-sourcetrail#48]
Hello and thank you for viewing the issue.
I have been using Visual Studio 2019 Preview for more than a month and I noticed some improvements in performance and startup time.I want to use  SourceTrail with it, but I can't install the extension since is not compatible with the IDE.
Can anybody help me solve this ? Can some modifications to the .vsix extension solve the problem or it is another solution ? 
Thank you !

**Comment by cata0309** [comment]
Any ideas?

**Comment by mlangkabel** [comment]
H @cata0309, thanks for bringing this up. Can you please try to download and install the following package to your VS2019 installation?

[vs-sourcetrail.zip](https://github.com/CoatiSoftware/vs-sourcetrail/files/2754467/vs-sourcetrail.zip)

If that works for you, we will adjust the build file here on the repo and issue a new release :)

**Comment by cata0309** [comment]
![image](https://user-images.githubusercontent.com/35623921/51120659-422f6a80-181e-11e9-8df1-995a3a2e6486.png)
I can't install it, unfortunately

**Comment by cata0309** [comment]
![image](https://user-images.githubusercontent.com/35623921/51120759-7e62cb00-181e-11e9-9b4a-e6d484eaa561.png)
I think there must pe a 2019 enginewrapper and must be linked to the manifest.json file and changed the version area of the core editor and the IDE itself to cover 16 and above versions of Visual studio IDE.
Just some ideas.

**Comment by cata0309** [comment]
I tried to make a copy of the 2017 engine wrapper and decompile it in Jetbrains's IDE dotPeek and modify it to support 2019 version, but no succes.

**Comment by cata0309** [comment]
What do you think @mlangkabel ?

**Comment by mlangkabel** [comment]
Thanks for testing. I just found out that we missed to extend the accepted version of one prerequisite of the plugin to VS2019.

Please try to run this installer:
[vs-sourcetrail.zip](https://github.com/CoatiSoftware/vs-sourcetrail/files/2755864/vs-sourcetrail.zip)

If that lets you install the extension, we know that VS2019 compatibility is possible and we need to add VCProjectEngineWrappers for VS2019 to properly implement the core functionality - as you already pointed out :)

**Comment by cata0309** [comment]
It's working for now, I will test it some days and if I have any problem with it I will comment on this issue

**Comment by cata0309** [comment]
Thank you

**Comment by mlangkabel** [comment]
Thanks for testing! So now that the installer is working we need to add those wrappers for VS2019. I will create a branch for that now.

**Comment by cata0309** [comment]
No problem, I love to help

**Comment by CoolOppo** [comment]
Would love to have this for VS 2019. Currently I'm only keeping VS 2017 installed in case I need to use this extension.

**Comment by mlangkabel** [comment]
Implemented with merge of pull request #54
