### ISSUE TITLE
Exception at "Create Compilation Database" 

### ISSUE THREAD

**Issue by GitGoogol** [CoatiSoftware/vs-sourcetrail#57]
By trying to create the compilation database from Sourcetrail, the Sroucetrail log in Visual Studio shows the following Exception:
`Info: Received request to create a compilation database.`
`Error: Excpetion: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.`

Setup:
Visual Studio Version 2015
Sourcetrail Extension 2.0.1.125
Sourcetrail 2019.1.11 - 64 bit

**Comment by mlangkabel** [comment]
Thanks for reporting! Yesterday I fixed a similar issue that happened when navigating to a location in VS from Sourcetrail. So it should be easily fixable. 
For now you can just use "Sourcetrail->Create Compilation Database"  from the VS menu bar as a workaround.

**Comment by mlangkabel** [comment]
Fixed with version 2.0.2
