### ISSUE TITLE
create compilation_database grayed in vs2019 professional edition 16.2.1

### ISSUE THREAD

**Issue by abelZ** [CoatiSoftware/vs-sourcetrail#59]
this is the logs:
18:12:50	INFO	SourcetrailExtensionPackage.cs:363 (InitLogging)		Logging initialized for Sourcetrail Extension 2.0.2.128
18:12:51	INFO	SourcetrailExtensionPackage.cs:337 (InitNetwork)		Initializing Network with Server Port 6666 and Client Port 6667
18:12:53	ERROR	NetworkUtility.cs:173 (Send)		Exception: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:6667
18:12:53	INFO	SourcetrailExtensionPackage.cs:253 (InitializeAsync)		Initialization done

**Comment by gilmanjo** [comment]
Having the same issue in 2017.

**Comment by gilmanjo** [comment]
Error: Exception: Thread was being aborted.
Error: Exception: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by mlangkabel** [comment]
It looks like the only way this can happen is when opening VS direclty on a solution file and not starting VS first and then opening a solution. This issue should be fixed by commit f458f94926f181b2f4236bb48c99e53cd7690df2. The fix has been published with release v2.0.3.
