### ISSUE TITLE
Why there are no headers (.h) in Compilation database JSON.

### ISSUE THREAD

**Issue by JamesWCCheng** [CoatiSoftware/vs-sourcetrail#63]
Hi,
I used this extension for generating compilation database with my Cpp Project.

But in the JSON file, only .cpp will be listed in. There is no .h header file inside.

Is this a known issue or anything I forgot to setup.

Thanks

I also asked here

https://marketplace.visualstudio.com/items?itemName=vs-publisher-1208751.SourcetrailExtension&ssr=false#qna

**Comment by mlangkabel** [comment]
This is intended behavior. The compiler starts a [translation unit](https://stackoverflow.com/questions/1106149/what-is-a-translation-unit-in-c) for each source file. The compilation database lists those source files and the flags to compile those files (e.g. defines, header search paths, etc.). Each header that is included in at least one source file gets compiled. Headers that are not encountered during compilation are ignored.

**Comment by JamesWCCheng** [comment]
The use case for me is to use this VS extension to generate compilation database JSON.

And then use clang-tidy.exe to fix my project.

If the compilation database isn't with headers, clang-tidy will not fix/detect the problems in the header files.

How could I make it work or find any workaround for this scenario?

**Comment by mlangkabel** [comment]
I just googled a little. Maybe this helps: https://stackoverflow.com/questions/35261868/getting-clang-tidy-to-fix-header-files
