### ISSUE TITLE
Unable to use on Unreal Engine

### ISSUE THREAD

**Issue by fire** [CoatiSoftware/vs-sourcetrail#7]
I was unable to use this tool on unreal engine sln.

**Comment by egraether** [comment]
Thanks for reporting!
+1 by mail

**Comment by fire** [comment]
It gives an empty json file on win64 development editor.

```
[

]``` 

Every time I try to demo sourcetrail on ue4, I had to manually set the include and search paths. Sourcetrail is phenomenal, but it wouldn't work for me or my acquaintances if it took 100s paths includes.

**Comment by egraether** [comment]
That is relateable of course. We will look into fixing this.

**Comment by fire** [comment]
Using:

Engine/Binaries/DotNET/UnrealBuildTool.exe -cmakefile -help -project="C:\game.uproject" -game -engine -progress

"C:\Program Files\CMake\bin\cmake.exe" --trace --debug-output -DCMAKE_EXPORT_COMPILE_COMMANDS=1 . -GNinja

Generates: compile_commands.json (2.2gb~)

This can be loaded inside of Sourcetrail.

**Comment by egraether** [comment]
Thank you for this information. Did you succeed in indexing UE4 with Sourcetrail?

**Comment by fire** [comment]
The cmake method did not generate proper include paths. No. :/

**Comment by mlangkabel** [comment]
When trying to reproduce your issue I followed [this setup guide](https://github.com/EpicGames/UnrealEngine/blob/release/README.md). Running `GenerateProjectFiles.bat` generates a `.sln` file that contains a Visual Studio Makefile Project. 

So it looks like this is the same as #8.

**Comment by fire** [comment]
Can you generate a build for this so I can test ue4?

**Comment by mlangkabel** [comment]
I've tried using the modified extension on ue4. It looks like it's working now but generating the Compilation Database was very slow. So I took an afternoon of profiling to figure out what exactly caused the slowdown and caught the performance issue.

We are planning to do a release tomorrow. Stay tuned ;)

**Comment by mlangkabel** [comment]
New version is published on the Visual Studio Marketplace. Should be available from inside your Visual Studio in a couple of minutes.
